name: Kenji's workflow to run commands inside a docker container
on: [push]

jobs:
  my_build_job:  
    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:main
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - name: Commands
        run: |
          whoami
          pwd
          hostname
          ls -al
          ls -al ../
          ls -al ../../
          ls -al /workdir
