name: Nordic 52840 CI/CD workflow
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:main
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - name: Go to project directory
        run: |
          cd /workdir/project
      - name: Checkout source code          
        uses: actions/checkout@v3
      - name: Build code
        run: |
          west build central_and_peripheral_hr -p always -b nrf52840dk_nrf52840 --build-dir /workdir/project/build
      - name: Prepare artifact
        run: |
          mkdir /workdir/project/artifacts
          cp /workdir/project/build/zephyr/zephyr.hex /workdir/project/artifacts/
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-to-download
          path: /workdir/project/artifacts/zephyr.hex
