name: Kenji's workflow to run commands inside a docker container
on: [push]

jobs:
  my_build_job:  
    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:main
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - name: Commands
        run: |
          cd /workdir/project
          ls -al
      - uses: actions/checkout@v3
      - name: Build
        run: |
          pwd
          ls -al
          west build central_and_peripheral_hr -p always -b nrf52840dk_nrf52840 --build-dir /workdir/project/build
      - name: Deploy
        run: |
          ls -al /workdir/project/build

